### PR TITLE
ProjectScaffold-ize

### PR DESCRIPTION
**Pull request by sideeffffect**
this adds support for cool stuff, like packaging, tests, etc

it might seem that there are many changes, but actually all that I've done is to remove trailing whitespace

you can enable Travis and AppVeyor -- do it even before the merge

### CODE REVIEW

**Comment by palladin** [comment]
Thanks!

**Comment by sideeffffect** [comment]
can you please enable both Travis and AppVeyor for this repo?

Here is howto for
Travis: https://travis-ci.org/getting_started
and
AppVeyor: https://www.appveyor.com/docs/

or just ask me if you need help with this ;)

**Comment by palladin** [comment]
Done https://travis-ci.org/palladin/Higher https://ci.appveyor.com/project/nessos/higher

**Comment by sideeffffect** [comment]
why `nessos` and not `palladin` on AppVeyor, if you don't mind me asking?
if it's not `palladin`, then we have to fix the Readme

**Comment by palladin** [comment]
I tried to change the account name to palladin and I broke all the links for the other hosted projects.
(btw nessos is the name of my company)

**Comment by sideeffffect** [comment]
fair enough
I've created fix https://github.com/palladin/Higher/pull/12
but I see that you have configured only Travis as a PR guard -- can you please make AppVeyor a mandatory pass for PRs to be mergable?

**Comment by palladin** [comment]
I think it is ready.

**Comment by sideeffffect** [comment]
I don't think so, if you look at https://github.com/palladin/Higher/pull/13 , only Travis got triggered
perhaps you have to change something in settings of the repository

http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests

https://stackoverflow.com/questions/32607885/appveyor-doesnt-update-github-pull-request-with-the-build-status

**Comment by palladin** [comment]
Hmmm, the webhook for appveyor is setup correctly and in Recent Deliveries I found your pull request "Small Readme change".

**Comment by palladin** [comment]
I think it is ok now 
https://github.com/palladin/Higher/pull/14

**Comment by sideeffffect** [comment]
yep, great!

**Pull request merged**
